---
traefik_package: traefik-1.0.0
traefik_marathon_endpoint: http://marathon.service.consul:18080
traefik_marathon_domain: marathon.localhost

# Do Marathon apps automatically get exposed (traefik default is false)
traefik_marathon_expose_by_default: "true"

traefik_routed_cert_path: ""
traefik_routed_key_path: ""
traefik_access_log_path: ""
traefik_loglevel: "ERROR"
traefik_retry_attempts: -1